name: Build and Deploy Drawing App

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build:web

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Get commit short SHA
        id: get_commit_sha
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_commit_sha.outputs.sha_short }}
          release_name: Release ${{ steps.get_commit_sha.outputs.sha_short }}
          body: |
            Drawing App Release ${{ steps.get_commit_sha.outputs.sha_short }}
            
            ## Downloads
            - Web version available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
            - Desktop versions available as attachments below
          draft: false
          prerelease: false

      - name: Upload Tauri binaries to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/appimage/drawing-app_*_amd64.AppImage
          asset_name: drawing-app-linux.AppImage
          asset_content_type: application/octet-stream

      - name: Upload Tauri binaries to Release (DMG)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/dmg/drawing-app_*_x64.dmg
          asset_name: drawing-app-macos.dmg
          asset_content_type: application/octet-stream

      - name: Upload Tauri binaries to Release (MSI)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/msi/drawing-app_*_x64_en-US.msi
          asset_name: drawing-app-windows.msi
          asset_content_type: application/octet-stream

      - name: Set GitHub Pages committer identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 